---
# yamllint disable rule:line-length

- name: Start interface
  # noqa: no-jinja-when
  ansible.builtin.command: ifup {{ item.key }}
  with_dict: "{{ interfaces_v4 }}"
  register: __result
  changed_when: "__result.rc != 0"
  when:
    - "ansible_{{ item.key | regex_replace(':', '_') | regex_replace('\\.', '_') }} is defined"
    - "'active' in ansible_{{ item.key | regex_replace(':', '_') | regex_replace('\\.', '_') }}"
    - "not ansible_{{ item.key | regex_replace(':', '_') | regex_replace('\\.', '_') }}['active']"
